import type { RaiseResult, DealResult } from "@/types";

export async function downloadRaisePDF(data: RaiseResult) {
  const jspdfModule = await import("jspdf");
  const jsPDF = jspdfModule.default ?? (jspdfModule as { jsPDF?: typeof jspdfModule.default }).jsPDF;
  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });

  const W = 210;
  const margin = 20;
  let y = 20;

  const line = () => {
    doc.setDrawColor(201, 168, 76);
    doc.setLineWidth(0.3);
    doc.line(margin, y, W - margin, y);
    y += 6;
  };

  // Header
  doc.setFillColor(8, 11, 15);
  doc.rect(0, 0, W, 297, "F");

  doc.setFont("helvetica", "bold");
  doc.setFontSize(10);
  doc.setTextColor(201, 168, 76);
  doc.text("MERIDIAN — CAPITAL RAISE BRIEF — CONFIDENTIAL", W / 2, y, { align: "center" });
  y += 8;

  line();

  doc.setFontSize(18);
  doc.setTextColor(240, 237, 230);
  doc.text(data.companyName, margin, y);
  y += 8;

  doc.setFontSize(9);
  doc.setTextColor(107, 114, 128);
  doc.text(`Sector: ${data.sector}  |  Stage: ${data.stage}  |  Raising: ${data.amount}  |  Geography: ${data.geography}`, margin, y);
  y += 4;
  line();

  // Company summary
  doc.setFontSize(9);
  doc.setTextColor(240, 237, 230);
  doc.setFont("helvetica", "normal");
  const summaryLines = doc.splitTextToSize(data.companySummary, W - margin * 2);
  doc.text(summaryLines, margin, y);
  y += summaryLines.length * 5 + 6;

  line();

  // Investors
  doc.setFont("helvetica", "bold");
  doc.setFontSize(10);
  doc.setTextColor(201, 168, 76);
  doc.text("MATCHED INVESTORS", margin, y);
  y += 7;

  data.investors.forEach((inv, i) => {
    if (y > 260) {
      doc.addPage();
      doc.setFillColor(8, 11, 15);
      doc.rect(0, 0, W, 297, "F");
      y = 20;
    }

    doc.setFont("helvetica", "bold");
    doc.setFontSize(10);
    doc.setTextColor(240, 237, 230);
    doc.text(`${i + 1}. ${inv.name}`, margin, y);

    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    doc.setTextColor(201, 168, 76);
    doc.text(inv.type, margin + doc.getTextWidth(`${i + 1}. ${inv.name}`) + 4, y);
    y += 5;

    doc.setTextColor(107, 114, 128);
    doc.text(`Cheque: ${inv.chequeSize}  |  Focus: ${inv.sectorFocus.join(", ")}  |  Geo: ${inv.geographicFocus}`, margin + 4, y);
    y += 5;

    doc.setTextColor(240, 237, 230);
    const fitLines = doc.splitTextToSize(inv.whyTheyFit, W - margin * 2 - 8);
    doc.text(fitLines, margin + 4, y);
    y += fitLines.length * 4 + 2;

    doc.setTextColor(107, 114, 128);
    doc.text(`Outreach: ${inv.outreachAngle}`, margin + 4, y);
    y += 4;

    const activityColors: Record<string, [number, number, number]> = {
      "Recently Active": [34, 197, 94],
      "Active": [201, 168, 76],
      "Quiet": [239, 68, 68],
      "Unknown": [107, 114, 128],
    };
    const [r, g, b] = activityColors[inv.fundActivity] ?? [107, 114, 128];
    doc.setTextColor(r, g, b);
    doc.text(`● ${inv.fundActivity}`, margin + 4, y);
    y += 7;
  });

  y += 4;
  line();

  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.setTextColor(107, 114, 128);
  doc.text(`Generated by Meridian — meridian.app  |  ${new Date().toLocaleDateString("en-GB", { year: "numeric", month: "long", day: "numeric" })}`, W / 2, y, { align: "center" });

  doc.save(`Meridian_Raise_Brief_${data.companyName.replace(/\s+/g, "_")}.pdf`);
}

export async function downloadDealPDF(data: DealResult) {
  const jspdfModule = await import("jspdf");
  const jsPDF = jspdfModule.default ?? (jspdfModule as { jsPDF?: typeof jspdfModule.default }).jsPDF;
  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });

  const W = 210;
  const margin = 20;
  let y = 20;

  doc.setFillColor(8, 11, 15);
  doc.rect(0, 0, W, 297, "F");

  const line = () => {
    doc.setDrawColor(201, 168, 76);
    doc.setLineWidth(0.3);
    doc.line(margin, y, W - margin, y);
    y += 6;
  };

  doc.setFont("helvetica", "bold");
  doc.setFontSize(10);
  doc.setTextColor(201, 168, 76);
  doc.text("MERIDIAN — DEAL SIGNAL REPORT — CONFIDENTIAL", W / 2, y, { align: "center" });
  y += 8;
  line();

  doc.setFontSize(18);
  doc.setTextColor(240, 237, 230);
  doc.text(data.companyName, margin, y);
  y += 7;

  doc.setFontSize(9);
  doc.setTextColor(107, 114, 128);
  doc.text(`Sector: ${data.sector}  |  Signal: ${data.signalStrength}  |  Confidence: ${data.dataConfidence}`, margin, y);
  y += 4;
  line();

  // Brief
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(240, 237, 230);
  const briefLines = doc.splitTextToSize(data.mandateBrief, W - margin * 2);
  doc.text(briefLines.slice(0, 60), margin, y);

  line();
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.setTextColor(107, 114, 128);
  doc.text(`Generated by Meridian — meridian.app  |  ${new Date().toLocaleDateString("en-GB", { year: "numeric", month: "long", day: "numeric" })}`, W / 2, 285, { align: "center" });

  doc.save(`Meridian_Deal_Brief_${data.companyName.replace(/\s+/g, "_")}.pdf`);
}
